CREATE TABLE USER(
 ID  VARCHAR(50) NOT NULL PRIMARY KEY COMMENT '아이디',
 PASS_WD VARCHAR(100) NOT NULL DEFAULT '' COMMENT '비밀번호',
 NAME VARCHAR(100)  NOT NULL DEFAULT '' COMMENT '이름',
 EMAIL VARCHAR(50) NOT NULL DEFAULT '' COMMENT '이메일',
 BIRTH VARCHAR(8)  NOT NULL DEFAULT '' COMMENT '생년월일',
 GENDER  VARCHAR(1)  NOT NULL DEFAULT 'f'  COMMENT '성별',
 TEL VARCHAR(30) NOT NULL DEFAULT '' COMMENT '연락처',
 ADULT_YN  VARCHAR(1)  NOT NULL DEFAULT '' COMMENT '19세 이상여부',
 REG_DTM VARCHAR(14) NOT NULL COMMENT '등록일자',
 UPD_DTM VARCHAR(14) NOT NULL COMMENT '수정일자',
 USE_YN  VARCHAR(1)  NOT NULL COMMENT '사용여부'
) COMMENT '회원관리';

CREATE TABLE LOGINLOG(
	ID VARCHAR(50) NOT NULL COMMENT '회원 아이디',
	LOGIN_DT VARCHAR(8) NOT NULL COMMENT '로그인 일자',
	LOGIN_TM VARCHAR(6) NOT NULL COMMENT '로그인 시간'
) COMMENT '로그인 이력';