CREATE TABLE MENU(
	MENU_CD INT(4) PRIMARY KEY AUTO_INCREMENT COMMENT '그룹메뉴 ID',
	MENU_NM VARCHAR(50) NOT NULL DEFAULT '' COMMENT '그룹메뉴명',
	ORDER_NO INT(2) NOT NULL DEFAULT 0 COMMENT '메뉴순서',
	LINK_URL VARCHAR(100) NOT NULL DEFAULT '' COMMENT '링크 URL',
	REG_DTM VARCHAR(14) NOT NULL COMMENT '등록일자',
	UPD_DTM VARCHAR(14) NOT NULL COMMENT '수정일자'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci COMMENT '그룹메뉴 관리';

CREATE TABLE SUBMENU(
	MENU_CD INT(4) COMMENT '그룹메뉴 ID',
	SUB_MENU_CD INT(4) COMMENT '서브메뉴 ID',
	SUB_MENU_NM VARCHAR(50) NOT NULL DEFAULT '' COMMENT '서브메뉴명',
	ORDER_NO INT(2) NOT NULL DEFAULT 0 COMMENT '메뉴순서',
	USER_AUTH VARCHAR(1) NOT NULL DEFAULT 'C' COMMENT '계정권한',
	LINK_URL VARCHAR(100) NOT NULL DEFAULT '' COMMENT '링크 URL',
	USE_YN VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '사용여부',
	REG_DTM VARCHAR(14) NOT NULL COMMENT '등록일자',
	UPD_DTM VARCHAR(14) NOT NULL COMMENT '수정일자',
	PRIMARY KEY(MENU_CD, SUB_MENU_CD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE utf8_general_ci COMMENT '서브메뉴 관리';
