-- 타투 상품 테이블
CREATE TABLE TATTOO (
	ID INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '타투상품 ID',
	NM VARCHAR(100) NOT NULL DEFAULT '' COMMENT '타투상품명',
	GOODS VARCHAR(50) NOT NULL DEFAULT '' COMMENT '타투상품 부위',
	IMAGE VARCHAR(200) COMMENT '상품 메인이미지',
	PRICE INT(8) DEFAULT 0 COMMENT '타투상품 가격',
	COLOR VARCHAR(30) DEFAULT '' COMMENT '타투상품 색상',
	SALE INT(3) DEFAULT 0 COMMENT '타투상품 할인률',
	SALE_START_DT VARCHAR(8) NOT NULL DEFAULT '' COMMENT '할인 시작일자',
	SALE_END_DT VARCHAR(8) NOT NULL DEFAULT '' COMMENT '할인 종료일자',
	CONTENT LONGTEXT NOT NULL DEFAULT '' COMMENT '타투상품 내용',
	REG_DTM VARCHAR(14) NOT NULL COMMENT '등록일자',
	UPD_DTM VARCHAR(14) NOT NULL COMMENT '최종수정일자',
	DEL_YN VARCHAR(1) NOT NULL DEFAULT 'N' COMMENT '삭제여부'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT '타투 상품 테이블'; 
ALTER TABLE TATTOO ADD INDEX TATTOO_IDX01 (GOODS);

-- 담당자 테이블
CREATE TABLE TATTOOIST(
	SEQ INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '담당자 ID',
	NAME VARCHAR(50) NOT NULL DEFAULT '' COMMENT '담당자 명',
	CAREER INT(3) DEFAULT 0 COMMENT '경력',
	REQ_DTM VARCHAR(14) NOT NULL COMMENT '등록일자',
	UPD_DTM VARCHAR(14) NOT NULL COMMENT '최종수정일자'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 ;

-- 타투 색상 테이블
CREATE TABLE TATTOOCOLOR(
	SEQ INT(10) PRIMARY KEY AUTO_INCREMENT COMMENT '색상 ID',
	COLOR VARCHAR(30) DEFAULT '' COMMENT '타투상품 색상'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;




-- 구매내역 테이블
유저ID
상품ID
구매일시
SIZE VARCHAR(20) DEFAULT '' COMMENT '타투상품 사이즈',
RESERVATION INT(3) NOT NULL DEFAULT 0 COMMENT '예약인원수',
	RESERVATION_DT VARCHAR(12) NOT NULL COMMENT '방문예약일시',
	TATTOOIST_ID VARCHAR(50) NOT NULL DEFAULT '' COMMENT '담당자 ID',
	
	